
name: Execute notebooks weekly

on:
  schedule:
    - cron: "0 12 * * 1"  # Mondays at 12:00 UTC
  workflow_dispatch:

jobs:
  run-papermill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute starter notebook
        run: |
          papermill notebooks/00_template.ipynb notebooks/00_template_out.ipynb -k python3
